### ISSUE TITLE
[MB2 feedback] DESCRIPTION is missing Imports

### ISSUE THREAD

**Issue by 16EAGLE** [clearclar/trajectoree#1]
Nice package!

The `DESCRIPTION` file of `trajectoree` is missing the field `Imports`, declaring packages that must be installed. Thus, auto-installation of dependencies, e.g. using `remotes::install_github("clearclar/trajectoree", dependencies =  T)` , fails if one tries to install the package without having the dependency packages already installed from which functions are imported, as declared in `NAMESPACE`.

**Comment by claravydra** [comment]
thanks! fixed it
